name: ishiki
description: A short game for the 2nd Flame Engine Game Jam.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  flame: ^1.3.0
  flame_audio: ^1.3.1
  flame_splash_screen: ^0.1.0
  provider: ^6.0.3
  bonfire: ^2.8.0
  flutter_web_buttons: ^0.0.8
  flutter_animator: ^3.2.2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/audio/
    - assets/audio/sfx/
    - assets/audio/bgm/
    - assets/fonts/
    - assets/images/
    - assets/images/tiled/

  fonts:
    - family: 1bit
      fonts:
        - asset: assets/fonts/Fool.ttf
